unbreak build with llvm-16 by including sys/types.h for __BEGIN_HIDDEN_DECLS
/usr/src/lib/libcrypto/whrlpool/wp_local.h:5:1: error: unknown type name '__BEGIN_HIDDEN_DECLS'

ok tb@

(cherry picked from commit 8e130001a169ea2bc5ef7489f8006e76fc2dc12f)