Replay "Add bus_dmamem_alloc_range(9) to riscv64, now required by [...]"
Unbreaks build for at least IP30.mp, otherwise kernel build breaks due to
`-Werror`:
```
[...]
cc  -g -Werror -Wall -Wimplicit-function-declaration  -Wno-uninitialized -Wno-pointer-sign  -Wframe-larger-than=2047 -mno-abicalls  -msoft-float -G 0 -ffreestanding  -O2  -pipe -nostdinc -I/sys -I/sys/arch/sgi/compile/GENERIC-IP30.MP/obj -I/sys/arch -DDDB -DDIAGNOSTIC -DKTRACE -DACCOUNTING -DKMEMSTATS -DPTRACE -DPOOL_DEBUG -DCRYPTO -DSYSVMSG -DSYSVSEM -DSYSVSHM -DUVM_SWAP_ENCRYPT -DFFS -DFFS2 -DUFS_DIRHASH -DQUOTA -DEXT2FS -DMFS -DNFSCLIENT -DNFSSERVER -DCD9660 -DUDF -DMSDOSFS -DFIFO -DFUSE -DSOCKET_SPLICE -DTCP_ECN -DTCP_SIGNATURE -DINET6 -DIPSEC -DPPP_BSDCOMP -DPPP_DEFLATE -DPIPEX -DMROUTING -DMPLS -DBOOT_CONFIG -DKERNBASE="0xa800000020000000" -DPCIVERBOSE -DUSER_PCICONF -DUSBVERBOSE -DTGT_OCTANE -DTGT_COHERENT -DARCBIOS -DCPU_R10000 -DONEWIREVERBOSE -DMULTIPROCESSOR -DMAXUSERS=32 -D_KERNEL -D__sgi__ -MD -MP  -c /sys/dev/pci/envy.c
[...]
cc1: warnings being treated as errors
/sys/dev/pci/envy.c: In function 'envy_allocm':
/sys/dev/pci/envy.c:1828: warning: implicit declaration of function 'bus_dmamem_alloc_range'
*** Error 1 in /sys/arch/sgi/compile/GENERIC-IP30.MP (Makefile:664 'envy.o')
*** Error 1 in target 'envy.o'
   14m27.69s real    23m58.74s user     3m20.45s system
2
```

See 925808ae053bc741e6f9c503a5d5d1d92f825ec1.